[project]
name = "circle-of-life-ai"
version = "0.1.0"
description = "Circle of Life MCP backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "psycopg2-binary",
    "boto3",
    "mcp-server",
    "pytest",
    "asyncpg",        
    "aioboto3",
    "pytest-asyncio", 
    "SQLAlchemy",
    "alembic",
    "sentence-transformers"
]
[tool.pytest.ini_options]
pythonpath = ["."]
